language: go
go:
  - "1.21"

services:
  - docker

notifications:
  email: false

env:
  - GO111MODULE=on GOTIFY_VERSIONS="v2.4.0 v2.3.0 v2.2.5 v2.2.4 v2.2.3 v2.2.2 v2.2.1 v2.2.0 v2.1.7 v2.1.6 v2.1.5 v2.1.4"

before_install:
  - make download-tools
  - go get -d

script:
  - go test ./...
  - >
    for TARGET in $GOTIFY_VERSIONS; do
      make GOTIFY_VERSION="$TARGET" FILE_SUFFIX="-for-gotify-$TARGET" build;
    done

deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: build/*.so
    skip_cleanup: true
    on:
      tags: true
